version: '2'

services:

  elasticsearch:
    image: elasticsearch:$ELK_VERSION
    volumes:
      - /home/ubuntu/rancher-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    labels:
      io.rancher.scheduler.affinity:host_label: elk=true
      elk: 'true'
    networks:
      - elk

  logstash:
    image: logstash:$ELK_VERSION
    volumes:
      - /home/ubuntu/rancher-elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /home/ubuntu/rancher-elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    labels:
      io.rancher.scheduler.affinity:host_label: elk=true
      elk: 'true'
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:$ELK_VERSION
    volumes:
      - /home/ubuntu/rancher-elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    labels:
      io.rancher.scheduler.affinity:host_label: elk=true
      elk: 'true'
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: guisen/filebeat
    volumes:
      - /home/ubuntu/rancher-elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/ubuntu/rancher-elk/filebeat/filebeat.template.json:/usr/share/filebeat/filebeat.template.json
      - /var/lib/docker/containers:/usr/share/dockerlogs/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.scheduler.affinity:host_label: elk=true
      elk: true
    networks:
      - elk
    depends_on:
      - logstash
    restart: on-failure

networks:

  elk:
    driver: bridge
